export enum ConfigKey {
  NODE_ENV = 'NODE_ENV',
  PORT = 'PORT',
  CORS_ORIGIN = 'CORS_ORIGIN',

  DATABASE_HOST = 'DATABASE_HOST',
  DATABASE_PORT = 'DATABASE_PORT',
  DATABASE_USER = 'DATABASE_USER',
  DATABASE_PASSWORD = 'DATABASE_PASSWORD',
  DATABASE_NAME = 'DATABASE_NAME',
  DATABASE_SYNC = 'DATABASE_SYNC',
  DATABASE_SSL = 'DATABASE_SSL',

  JWT_SECRET = 'JWT_SECRET',
  JWT_EXPIRES_IN = 'JWT_EXPIRES_IN',

  BCRYPT_SALT_ROUNDS = 'BCRYPT_SALT_ROUNDS',
}
